preset: recommended
risky: true
finder:
    exclude:
        - vendor
    name: "*.php"

disabled:
    - align_double_arrow
    - phpdoc_align
    - trailing_comma_in_multiline_array
    - phpdoc_to_comment
    - concat_without_spaces
