version: 2
jobs:

    build:
        docker:
            - image: circleci/php:7.2-browsers
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "composer.json" }}
                    - v1-dependencies-
            - run:
                name: Composer Install
                command: composer install -n --prefer-dist
            - save_cache:
                 paths:
                     - ./vendor
                 key: v1-dependencies-{{ checksum "composer.json" }}
            - run:
                 name: Test
                 command: composer test-all

    test-with-skeleton-app:
        docker:
            - image: circleci/php:7.2-browsers
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: Build and test skeleton app
                command: .circleci/build-and-test-skeleton.sh

    code-analyze:
        docker:
            - image: circleci/php:7.2-browsers
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "composer.json" }}
                    - v1-dependencies-
            - run:
                name: Set up Sonarcloud client
                command:
                    bash .circleci/setup-sonarcloud.sh
            - run:
                name: Add sonar dir to PATH
                command:
                    source $BASH_ENV
            - run:
                name: Check Sonarcloud setup
                command:
                    sonar-scanner --version
            - run:
                name: Composer Install
                command: composer install -n --prefer-dist
            - run:
                 name: Test coverage
                 command: vendor/bin/phpunit --coverage-clover coverage.xml --log-junit test-report.xml
            - run:
                name: Run sonar console
                command: |
                    sonar-scanner \
                        -Dsonar.projectKey=$SONARCLOUD_PROJECT \
                        -Dsonar.organization=$SONARCLOUD_ORGANIZATION \
                        -Dsonar.sources=src \
                        -Dsonar.host.url=$SONARCLOUD_URL \
                        -Dsonar.login=$SONARCLOUD_LOGIN \
                        -Dsonar.exclusions=logs/**,vendor/** \
                        -Dsonar.php.tests.reportPath=test-report.xml \
                        -Dsonar.php.coverage.reportPaths=coverage.xml
            - run:
                 name: Run codecov
                 command: bash <(curl -s https://codecov.io/bash)

workflows:
    version: 2
    standard:
        jobs:
            - build
            - test-with-skeleton-app:
                requires:
                    - build
            - code-analyze:
                requires:
                    - test-with-skeleton-app
